PN-1644: add second iuv management
pagopa/pn-delivery pull request #125
Opened 2022-07-05 08:54 UTC by masciale89

2022-07-05 13:22 UTC, MTurraPpa requested changes

2022-07-05 13:22 UTC, MTurraPpa commented on docs/openapi/schemas-pn-notification-v1.yaml
> +        creditorTaxId_optional:
Il creditorTaxId è unico, cambia solo il noticeCode

2022-07-05 13:22 UTC, MTurraPpa commented on src/main/java/it/pagopa/pn/delivery/svc/NotificationPriceService.java
> +                            .filter( tle -> TimelineElementCategory.REFINEMENT.equals(tle.getCategory()) || TimelineElementCategory.NOTIFICATION_VIEWED.equals( tle.getCategory() ))
perchè questa modifica? non mi sembra correlata alla issue

2022-07-05 13:22 UTC, MTurraPpa commented on src/main/java/it/pagopa/pn/delivery/svc/search/NotificationRetrieverService.java
> +		log.debug( "Set IUV to return" );
Log errato? E' compute IUV to return.
Utilizzerei compute NoticeCode invece di IUV.

2022-07-05 13:22 UTC, MTurraPpa commented on src/main/java/it/pagopa/pn/delivery/svc/search/NotificationRetrieverService.java
> +	private void findAndSetIUVToReturn(InternalNotification notification, List<TimelineElement> timelineElementList) {
Passerei al metodo già il giorno corretto invece ch passare tutta la timeline. Non è possibile calcolarlo nel metodo sopra. Bisogna cercare di passare solo lo stretto necessario, altrimenti si rischia che avendo oggetti complessi venga la tentazione di utilizzare questo metodo per fare altro. Mi aspetterei un metodo che dato la data di perfezionamento, la data attuale e i due noticeCode mi restituisca quello corretto.

2022-07-05 13:22 UTC, MTurraPpa commented on src/main/java/it/pagopa/pn/delivery/svc/search/NotificationRetrieverService.java
> +						default: {
mi sembra uguale al caso 1?

2022-07-05 14:13 UTC, masciale89 commented on src/main/java/it/pagopa/pn/delivery/svc/NotificationPriceService.java
> +                            .filter( tle -> TimelineElementCategory.REFINEMENT.equals(tle.getCategory()) || TimelineElementCategory.NOTIFICATION_VIEWED.equals( tle.getCategory() ))
perfezionamento sia per elemento di timeline REFINEMENT che per NOTIFICATION_VIEWED

2022-07-05 16:06 UTC, masciale89 commented on src/main/java/it/pagopa/pn/delivery/svc/search/NotificationRetrieverService.java
> +						paymentInfo.setCreditorTaxId( null );
Giusto togliere anche il CF dell'ente creditore?

2022-07-05 16:32 UTC, MTurraPpa approved these changes

2022-07-05 17:03 UTC, MTurraPpa commented on src/main/java/it/pagopa/pn/delivery/svc/search/NotificationRetrieverService.java
> +						paymentInfo.setCreditorTaxId( null );
no

2022-07-06 09:40 UTC, MTurraPpa approved these changes

2022-07-06 10:28 UTC, merged