PN-2140: first API fix for AGID
pagopa/pn-delivery pull request #185
Opened 2022-09-07 11:20 UTC by masciale89

2022-09-07 12:49 UTC, MTurraPpa requested changes
Usa la linea di comando https://github.com/italia/api-oas-checker#modalit%C3%A0-online

2022-09-08 13:57 UTC, MTurraPpa approved these changes

2022-09-09 15:39 UTC, fabriziolana approved these changes

2022-09-13 08:04 UTC, masciale89 commented on docs/openapi/api-internal-b2b-pa-v1.yaml
> +  "/status":
aperta issue PN-2168 per esporre path /status su downtime-logs

2022-09-13 08:05 UTC, merged