Feature/pn 1950
pagopa/pn-delivery pull request #186
Opened 2022-09-07 15:02 UTC by fabriziolana

2022-09-07 15:25 UTC, fabriziolana commented on src/test/java/it/pagopa/pn/delivery/svc/NotificationAttachmentServiceTest.java
> +        assertThrows(PnNotFoundException.class, () -> attachmentService.downloadAttachmentWithRedirect(
check

2022-09-08 08:44 UTC, masciale89 requested changes

2022-09-08 08:44 UTC, masciale89 commented on docs/openapi/api-internal-b2b-pa-v1.yaml
> +            application/json:
utilizziamo application/problem+json come da linee guida AGID

2022-09-08 08:44 UTC, masciale89 commented on src/main/java/it/pagopa/pn/delivery/springbootcfg/PnResponseEntityExceptionHandlerActivation.java
> +}
new line

2022-09-08 09:02 UTC, masciale89 approved these changes

2022-09-08 09:11 UTC, merged