PN-2631 aggiunta API per IO con una response più leggera
pagopa/pn-delivery pull request #273
Opened 2022-11-17 14:21 UTC by vincenzo-racca-pa

Aggiunta API V2 per IO APP

2022-11-17 16:38 UTC, masciale89 requested changes

2022-11-18 11:19 UTC, vincenzo-racca-pa commented on docs/openapi/appio/api-external-b2b-appio-v1.yaml
>    "/delivery/notifications/received/{iun}":
modificata versione in 1.1.0 nell'ultimo commit

2022-11-18 11:27 UTC, vincenzo-racca-pa commented on docs/openapi/api-internal-web-recipient-v1.yaml
> +        Le informazioni riguardanti una richiesta di notifica accettata e il processo di
Modificata descrizione e e nome del DTO di risposta in IOReceivedNotification

2022-11-18 11:28 UTC, vincenzo-racca-pa commented on docs/openapi/api-external-web-recipient-v1.yaml
> +  "/delivery/notifications/v2/received/{iun}":
fatto nell'ultimo commit

2022-11-18 11:47 UTC, MTurraPpa commented on docs/openapi/api-internal-web-recipient-v1.yaml
> +  "/delivery/notifications/v2/received/{iun}":                                                                # NO EXTERNAL
Perché anche qua?

2022-11-18 11:51 UTC, vincenzo-racca-pa commented on docs/openapi/api-internal-web-recipient-v1.yaml
> +  "/delivery/notifications/v2/received/{iun}":                                                                # NO EXTERNAL
Perché aggiungendo qui l'API, poi viene auto-generato il codice Java Server Side per chiamare poi effettivamnete l'API. Ti torna?

2022-11-23 09:48 UTC, vincenzo-racca-pa commented on docs/openapi/api-internal-web-recipient-v1.yaml
> +            $ref: '#/components/schemas/NotificationRecipient'                            # NO EXTERNAL
Dopo l'ultimo commit, i file api-internal-web-recipient-v1.yaml e api-external-web-recipient-v1.yaml sono stati revertati (sono uguali alla versione del ramo develop)

2022-11-23 09:50 UTC, MTurraPpa approved these changes

2022-11-29 15:56 UTC, MTurraPpa approved these changes

2022-12-05 09:51 UTC, MTurraPpa approved these changes

2022-12-05 10:17 UTC, masciale89 approved these changes

2022-12-05 10:26 UTC, merged