aggiornamento swagger
pagopa/pn-delivery pull request #299
Opened 2022-12-16 16:22 UTC by MicheleLaMacchiaNTT

- inserite variabili ad inizio file con id
- inserito valore pnTemporaryDocument = 1
- allineamento internal-to-external

2022-12-16 16:45 UTC, MTurraPpa requested changes
Scusa Michele, il file temp vengono tenuti 7gg

2022-12-16 16:45 UTC, MTurraPpa commented on docs/openapi/api-external-b2b-pa-v1.yaml
> +      <em>I documenti memorizzati su bucket S3  durante la fase di caricamento (1.a e 1.b) vengono mantenuti per <span id="pnTemporaryDocument">1 giorno</span>, passati i quali vengono eliminati ed a
Anche qua 7gg

2022-12-16 16:55 UTC, MicheleLaMacchiaNTT commented on docs/openapi/api-external-b2b-pa-v1.yaml
> +# <span id="pnTemporaryDocument">1 giorno</span> configurazione per file temporanei caricati prima dell'inserimento notifica, definito in storageConfigurations name: PN_TEMPORARY_DOCUMENT in pn-safes
aggiornato il valore pnTemporaryDocument a 7 giorni

2022-12-16 16:55 UTC, MicheleLaMacchiaNTT commented on docs/openapi/api-internal-b2b-pa-v1.yaml
> +      <em>I documenti memorizzati su bucket S3  durante la fase di caricamento (1.a e 1.b) vengono mantenuti per <span id="pnTemporaryDocument">1 giorno</span>, passati i quali vengono eliminati ed a
aggiornato il valore pnTemporaryDocument a 7 giorni

2022-12-19 08:04 UTC, MTurraPpa approved these changes

2022-12-19 08:04 UTC, merged