PN-5691: fix policy for DynamoDb
pagopa/pn-delivery pull request #456
Opened 2023-05-02 15:53 UTC by SimoneMartelliNTTD

2023-05-02 16:33 UTC, marco-vit-pagopa requested changes

2023-05-02 16:33 UTC, marco-vit-pagopa commented on scripts/aws/cfn/microservice.yml
> +              - 'dynamodb:BatchWriteItem'
@SimoneMartelliNTTD @MTurraPpa 
Se l'operazione BatchWriteItem viene utiizzata sulla tabella pn-Notifications mi serve di saperlo esplicitamente perché può impattare alcuni aspetti degli stream kinesis verso DataLake.
Se viene usata solo su altre tabelle è opportuno utilizzare uno statement separato per non dare questo diritto all'applicazione. Mi riferisco al diritto di BatchWriteItem sulla tabella pn-Notifications

2023-05-03 06:40 UTC, MTurraPpa approved these changes

2023-05-03 14:54 UTC, marco-vit-pagopa approved these changes

2023-05-03 14:56 UTC, merged