feature/PN-7841
pagopa/pn-delivery pull request #577
Opened 2023-09-22 07:44 UTC by masciale89

2023-09-28 15:41 UTC, FeliceMente requested changes

2023-09-28 15:41 UTC, FeliceMente commented on scripts/aws/cfn/microservice.yml
> +      GroupDescription: !Sub '${VersioningV1V21SendNewNotificationLambdaName}-sec-group'
VersioningV1V21SendNewNotificationLambdaName va dichiarato in storage.yml. Questo è un esempio da un'altra lambda:

  VersioningV1V2GetNotificationLambdaName:
    Value: !Sub "${ProjectName}-delivery-versioning-v1v2-getnotification-lambda"

2023-09-28 15:41 UTC, FeliceMente commented on scripts/aws/cfn/microservice.yml
> +      GroupDescription: !Sub '${VersioningV1V21SendNewNotificationLambdaName}-sec-group'
in storage.yml va anche definito un log group associato alla lambda. Questo è un esempio:
  VersioningV1V2GetNotificationLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-delivery-versioning-v1v2-getnotification-lambda"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

2023-09-29 09:36 UTC, fdammassa approved these changes
@masciale89 approvato per quanto riguarda infra

2023-09-29 09:55 UTC, merged