Aggiornamento swagger
pagopa/pn-delivery pull request #676
Opened 2023-12-21 12:07 UTC by MicheleBellizziNTT

Aggiornato punto 2 e puntamenti ai legal fact

2023-12-21 12:14 UTC, masciale89 requested changes

2023-12-21 12:14 UTC, masciale89 commented on docs/openapi/api-internal-b2b-pa.yaml
> +      E' possibile scaricare le Attestazioni Opponibili a Terzi e gli altri documenti conservati da Piattaforma Notifiche attraverso il servizio di [dowload Legal Fact](#/SenderReadB2B/retrieveSentNo
questa operationId non mi risulta corretta

2023-12-21 12:28 UTC, MicheleBellizziNTT commented on docs/openapi/api-internal-b2b-pa.yaml
> +      E' possibile scaricare le Attestazioni Opponibili a Terzi e gli altri documenti conservati da Piattaforma Notifiche attraverso il servizio di [dowload Legal Fact](#/SenderReadB2B/retrieveSentNo
io ho trovato questa:
   - LegalFacts
      operationId: getLegalFactById                                      # NO EXTERNAL
#      operationId: downloadLegalFactById                                # ONLY EXTERNAL

2024-01-10 11:29 UTC, masciale89 approved these changes

2024-05-03 14:11 UTC, fabriziolana commented
Ho riportato le modifiche nel branch bug/PN-10784, chiudo questa  PR

2024-05-03 14:11 UTC, closed without merging